// Code generated by goctl. DO NOT EDIT!
// Source: abtest.proto

package usecase

import (
	"context"

	"shorturl/rpc/abtest/abtest"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AbReq = abtest.AbReq
	AbRsp = abtest.AbRsp

	Usecase interface {
		Usecase(ctx context.Context, in *AbReq, opts ...grpc.CallOption) (*AbRsp, error)
	}

	defaultUsecase struct {
		cli zrpc.Client
	}
)

func NewUsecase(cli zrpc.Client) Usecase {
	return &defaultUsecase{
		cli: cli,
	}
}

func (m *defaultUsecase) Usecase(ctx context.Context, in *AbReq, opts ...grpc.CallOption) (*AbRsp, error) {
	client := abtest.NewUsecaseClient(m.cli.Conn())
	return client.Usecase(ctx, in, opts...)
}
