// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: abtest.proto

package abtest

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UsecaseClient is the client API for Usecase service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UsecaseClient interface {
	Usecase(ctx context.Context, in *AbReq, opts ...grpc.CallOption) (*AbRsp, error)
}

type usecaseClient struct {
	cc grpc.ClientConnInterface
}

func NewUsecaseClient(cc grpc.ClientConnInterface) UsecaseClient {
	return &usecaseClient{cc}
}

func (c *usecaseClient) Usecase(ctx context.Context, in *AbReq, opts ...grpc.CallOption) (*AbRsp, error) {
	out := new(AbRsp)
	err := c.cc.Invoke(ctx, "/abtest.usecase/usecase", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsecaseServer is the server API for Usecase service.
// All implementations must embed UnimplementedUsecaseServer
// for forward compatibility
type UsecaseServer interface {
	Usecase(context.Context, *AbReq) (*AbRsp, error)
	mustEmbedUnimplementedUsecaseServer()
}

// UnimplementedUsecaseServer must be embedded to have forward compatible implementations.
type UnimplementedUsecaseServer struct {
}

func (UnimplementedUsecaseServer) Usecase(context.Context, *AbReq) (*AbRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Usecase not implemented")
}
func (UnimplementedUsecaseServer) mustEmbedUnimplementedUsecaseServer() {}

// UnsafeUsecaseServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UsecaseServer will
// result in compilation errors.
type UnsafeUsecaseServer interface {
	mustEmbedUnimplementedUsecaseServer()
}

func RegisterUsecaseServer(s grpc.ServiceRegistrar, srv UsecaseServer) {
	s.RegisterService(&Usecase_ServiceDesc, srv)
}

func _Usecase_Usecase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsecaseServer).Usecase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/abtest.usecase/usecase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsecaseServer).Usecase(ctx, req.(*AbReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Usecase_ServiceDesc is the grpc.ServiceDesc for Usecase service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Usecase_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "abtest.usecase",
	HandlerType: (*UsecaseServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "usecase",
			Handler:    _Usecase_Usecase_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "abtest.proto",
}
