// Code generated by goctl. DO NOT EDIT!
// Source: abtest.proto

package server

import (
	"context"

	"shorturl/rpc/abtest/abtest"
	"shorturl/rpc/abtest/internal/logic"
	"shorturl/rpc/abtest/internal/svc"
)

type UsecaseServer struct {
	svcCtx *svc.ServiceContext
	abtest.UnimplementedUsecaseServer
}

func NewUsecaseServer(svcCtx *svc.ServiceContext) *UsecaseServer {
	return &UsecaseServer{
		svcCtx: svcCtx,
	}
}

func (s *UsecaseServer) Usecase(ctx context.Context, in *abtest.AbReq) (*abtest.AbRsp, error) {
	l := logic.NewUsecaseLogic(ctx, s.svcCtx)
	return l.Usecase(in)
}
